### ISSUE TITLE
Missing libSM.so.6

### ISSUE THREAD

**Issue by ahron1** [AIGC-Audio/AudioGPT#57]
While following `run.md` to install and run the program on a Debian VM with NVIDIA A100 GPU, the last step gives a missing library error (below)

Google searches show that the missing library comes from OpenCV. `pip install opencv-python` says the requirements are already satisfied.

This is the error:

```
(audiogpt) root@debian-gpu4gb:~/AudioGPT# python audio-chatgpt.py  

root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.   

def backtrace(trace: np.ndarray): Traceback (most recent call last):   

File "audio-chatgpt.py", line 34, in <module>     
from audio_infer.pytorch.models import PVT   

File "/root/AudioGPT/audio_detection/audio_infer/pytorch/models.py", line 25, in <module>    from mmdet.utils import get_root_logger   

File "/root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/mmdet/__init__.py", line 2, in <module>     import mmcv   

File "/root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>     from .fileio import *   

File "/root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>     from .file_client import BaseStorageBackend, FileClient   

File "/root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>     from mmcv.utils.misc import has_method   

File "/root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 40, in <module>     from .env import collect_env   

File "/root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>     import cv2   

File "/root/miniconda3/envs/audiogpt/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>     from .cv2 import * 

ImportError: libSM.so.6: cannot open shared object file: No such file or directory 

(audiogpt) root@debian-gpu4gb:~/AudioGPT# 
```

**Comment by hsm207** [comment]
you also need to run `apt update && apt install -y libsm6 libxext6`
