### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by yosun** [AIGC-Audio/AudioGPT#75]
fresh install following run.md
```
python audio-chatgpt.py
Traceback (most recent call last):
  File "audio-chatgpt.py", line 9, in <module>
    import gradio as gr
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/gradio/components.py", line 32, in <module>
    from fastapi import UploadFile
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 39, in init pydantic.dataclasses
    # +=========+=========================================+
ImportError: cannot import name dataclass_transform
```

**Comment by yosun** [comment]
This resolved the error

```
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm

pip install numba --upgrade
```
