### ISSUE TITLE
Issue running the app

### ISSUE THREAD

**Issue by kuntal-c** [AIGC-Audio/AudioGPT#80]
After installing all necessary packages and dependencies including "mmdet", still keep getting the following error: 
Traceback (most recent call last):
  File "/Users/kc/AudioGPT/audio-chatgpt.py", line 34, in <module>
    from audio_infer.pytorch.models import PVT
  File "/Users/kc/AudioGPT/audio_detection/audio_infer/pytorch/models.py", line 25, in <module>
    from mmdet.utils import get_root_logger
ImportError: cannot import name 'get_root_logger' from 'mmdet.utils' (/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mmdet/utils/__init__.py)

**Comment by AccessRetrieved** [comment]
Same here. Using mmdet:
```
Name: mmdet
Version: 2.23.0
Summary: OpenMMLab Detection Toolbox and Benchmark
Home-page: https://github.com/open-mmlab/mmdetection
Author: MMDetection Contributors
Author-email: openmmlab@gmail.com
License: Apache License 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: matplotlib, numpy, pycocotools, six, terminaltables
Required-by:
```

Found this: https://github.com/open-mmlab/mmaction2/issues/768
Changed the maximum version in __init__.py to 2.23.0, and it works. But... found another bug: `ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mmcv/utils/__init__.py)`

Tried to install `mmcv-full`, but it's stuck on building the wheel for it for 30m now.
```
 ✘ jerryhu@Jerrys-MacBook-Pro  ~/projects/AudioGPT-main  pip install mmcv-full
Collecting mmcv-full
  Using cached mmcv-full-1.7.1.tar.gz (605 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mmcv-full) (2.4.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mmcv-full) (1.23.5)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mmcv-full) (21.3)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mmcv-full) (9.2.0)
Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mmcv-full) (6.0)
Requirement already satisfied: yapf in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mmcv-full) (0.33.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from packaging->mmcv-full) (3.0.9)
Requirement already satisfied: tomli>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yapf->mmcv-full) (2.0.1)
Building wheels for collected packages: mmcv-full
  Building wheel for mmcv-full (setup.py) ... -
```

**Comment by jjnyx** [comment]
anyone solved this issue?

**Comment by jjnyx** [comment]
Even though I changed the maximum version of mmcv, I still have the same error saying:

ImportError: cannot import name 'get_root_logger' from 'mmdet.utils' (/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mmdet/utils/init.py)

anyone resolved this issue?

**Comment by iBoostAI** [comment]
Installing mmcv-full can solve your problem, but this project still has too many issues and lacks detailed documentation. It's not worth wasting time on it.

> anyone resolved this issue?
